### ISSUE TITLE
Suggestion: Mark Duplicates when unit isnt ascended

### ISSUE THREAD

**Issue by Algraud** [Dae314/AFKBuilder#1]
Hello, really like the tool, but I wanted to offer a suggestion. The main rule people follow is dont upgrade to Legendary until you have 8 copies of a unit. It would help for wishlist planning and hero choice planning if you could mark how many copies you have and sort the list by them.

**Comment by Dae314** [comment]
Thanks for the feedback!  Are you thinking basically a textbox or number picker on each hero you own in the My Heroes area where you manually input the number of copies you have as well as accompanying sorting button (i.e. "sort by copies) in the filters area?

**Comment by Algraud** [comment]
Im not sure on the best implementation, but a number picker would probably be best (im not that good at UI design). The button in filters would also be awesome.

**Comment by Dae314** [comment]
Well I've been thinking about how to have players on desktop and mobile pick arbitrary numbers for engraving level, and this would pretty much need to follow along the same designs.  I'll wrap this into my work on the engraving info!

**Comment by Dae314** [comment]
With update 1.12.3, this feature has been added along with Engravings!
